# Generated by Django 3.2.1 on 2021-05-08 07:18

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_id', models.CharField(max_length=16)),
                ('ref_id', models.CharField(max_length=55)),
                ('card_holder_info', models.CharField(max_length=255)),
                ('sales_reference_id', models.CharField(max_length=55)),
                ('seen', models.BooleanField(default=False)),
                ('status', models.SmallIntegerField(choices=[(0, 'Created'), (1, 'verified'), (2, 'Failed'), (3, 'Settled')], default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('subscription_plan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.subscriptionplan')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
