# Generated by Django 3.2.3 on 2021-09-26 13:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='status',
            field=models.SmallIntegerField(choices=[(0, 'ایجاد شده'), (1, 'تایید شده'), (2, 'لغو شده'), (3, 'انجام شده')], default=0),
        ),
    ]
