# Generated by Django 3.1.7 on 2021-06-12 16:20

import discount_app.models
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Discount',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='', max_length=120, verbose_name='عنوان کد تخفیف')),
                ('code', models.CharField(blank=True, default=discount_app.models.generate_random_code, max_length=16, null=True, unique=True, verbose_name='کد تخفیف')),
                ('discount_percent', models.IntegerField(default=0, verbose_name='در صد کد تخفیف ')),
                ('valid_from', models.DateTimeField(blank=True, help_text=('در این فیلد تعیین کنید از چه زمانی کد تخفیف فعال باشد',), null=True, verbose_name='فعال از')),
                ('valid_to', models.DateTimeField(blank=True, help_text=('در  این فیلد تعریف کنید کد تخفیف تا چه زمانی فعال باشد',), null=True, verbose_name='زمان پایان')),
                ('active', models.BooleanField(default=True, verbose_name='وضعیت')),
            ],
            options={
                'verbose_name': 'کد تخفیف',
                'verbose_name_plural': 'کد های تخفیف',
            },
        ),
        migrations.CreateModel(
            name='CheckUserDiscount',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.BooleanField(blank=True, default=False, null=True, verbose_name='استفاده شده یا نه')),
                ('date_use', models.DateTimeField(auto_now_add=True)),
                ('discount', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='discount_app.discount', verbose_name='کد تخفیف')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='کاربر')),
            ],
            options={
                'verbose_name': 'دسترسی',
                'verbose_name_plural': 'دسترسی کد های  تخفیف',
            },
        ),
    ]
