# Generated by Django 3.1.7 on 2021-06-15 10:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('discount_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='checkuserdiscount',
            name='discount',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='discount', to='discount_app.discount', verbose_name='کد تخفیف'),
        ),
    ]
