# Generated by Django 3.2.3 on 2021-05-27 09:26

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Send_Message',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='عنوان ارسالی')),
                ('select', models.CharField(choices=[('e', 'ارسال ایمیل'), ('p', 'ارسال پیامک'), ('b', 'ارسال هردو')], max_length=1, verbose_name='نحوه ارسال')),
                ('message', models.TextField(verbose_name='پیام شما')),
                ('publish', models.DateTimeField(auto_now_add=True, verbose_name='زمان انتشار')),
                ('status', models.CharField(blank=True, choices=[('d', 'منتظر ارسال'), ('p', 'ارسال')], max_length=1, null=True, verbose_name='زمان ارسال')),
                ('active', models.BooleanField(default=True, verbose_name='وضعیت پیام')),
                ('users', models.ManyToManyField(related_name='all_user', to=settings.AUTH_USER_MODEL, verbose_name='اعضای را انتخاب کنید')),
            ],
            options={
                'verbose_name': 'ارسال',
                'verbose_name_plural': 'ارسالی به کاربران',
            },
        ),
    ]
