# Generated by Django 3.2.3 on 2021-06-18 14:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('movies', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='StartAppCnsr',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('s', models.CharField(default='00:00:00', max_length=8, verbose_name='زمان شروع')),
                ('e', models.CharField(blank=True, default='00:00:00', max_length=8, null=True, verbose_name='زمان پایان')),
                ('active', models.BooleanField(default=True, verbose_name='فعال')),
                ('episode', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='movies.episode', verbose_name='اپیزود')),
            ],
            options={
                'verbose_name': 'تیتراژ سانسور',
                'verbose_name_plural': 'تیتراژ سانسور ها',
                'ordering': ['episode__season__name', 'episode__index'],
            },
        ),
        migrations.CreateModel(
            name='MiddelAppCnsr',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('s', models.CharField(default='00:00:00', max_length=8, verbose_name='زمان شروع')),
                ('e', models.CharField(blank=True, default='00:00:00', max_length=8, null=True, verbose_name='زمان پایان')),
                ('active', models.BooleanField(default=True, verbose_name='فعال')),
                ('episode', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='movies.episode', verbose_name='اپیزود')),
            ],
            options={
                'verbose_name': 'سانسور',
                'verbose_name_plural': 'سانسور ها میان فیلم',
                'ordering': ['episode__season__name', 'episode__index'],
            },
        ),
        migrations.CreateModel(
            name='EndAppCnsr',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('s', models.CharField(default='00:00:00', max_length=8, verbose_name='زمان شروع')),
                ('e', models.CharField(blank=True, default='00:00:00', max_length=8, null=True, verbose_name='زمان پایان')),
                ('active', models.BooleanField(default=True, verbose_name='فعال')),
                ('episode', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='movies.episode', verbose_name='اپیزود')),
            ],
            options={
                'verbose_name': 'سانسور انتهایی',
                'verbose_name_plural': 'سانسور های انتهایی',
                'ordering': ['episode__season__name', 'episode__index'],
            },
        ),
    ]
