# Generated by Django 3.2.3 on 2021-06-19 18:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cnsr', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='middelappcnsr',
            options={'ordering': ['s', 'e'], 'verbose_name': 'سانسور', 'verbose_name_plural': 'سانسور ها میان فیلم'},
        ),
    ]
