# Generated by Django 3.2.3 on 2021-06-19 19:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cnsr', '0002_alter_middelappcnsr_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='endappcnsr',
            options={'ordering': ['episode__season__name', 'episode__index'], 'verbose_name': 'تیتراژ پایان', 'verbose_name_plural': 'تیتراژ پایان'},
        ),
        migrations.AlterModelOptions(
            name='middelappcnsr',
            options={'ordering': ['s', 'e'], 'verbose_name': 'تایم سانسور', 'verbose_name_plural': 'تایم سانسور'},
        ),
        migrations.AlterModelOptions(
            name='startappcnsr',
            options={'ordering': ['episode__season__name', 'episode__index'], 'verbose_name': 'تیتراژ آغاز', 'verbose_name_plural': 'تیتراژ آغاز'},
        ),
    ]
