# Generated by Django 3.2.3 on 2021-06-16 19:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='subscriptionplan',
            name='max_valid_days',
            field=models.PositiveSmallIntegerField(default=120),
        ),
        migrations.AddField(
            model_name='subscriptionplan',
            name='spacial_id',
            field=models.CharField(default='e8b3cb94', max_length=8),
        ),
    ]
