# Generated by Django 3.2.3 on 2021-06-16 20:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_auto_20210617_0023'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subscriptionplan',
            name='spacial_id',
            field=models.CharField(default='c7825aa6', max_length=8),
        ),
    ]
