# Generated by Django 3.2.3 on 2021-06-17 12:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_alter_subscriptionplan_spacial_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subscriptionplan',
            name='spacial_id',
            field=models.CharField(default='0ca1d8e2', max_length=8),
        ),
    ]
