# Generated by Django 3.2.3 on 2021-06-17 15:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0011_alter_subscriptionplan_spacial_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subscriptionplan',
            name='spacial_id',
            field=models.CharField(default='f1e5b9c8', max_length=8),
        ),
    ]
