# Generated by Django 3.2.3 on 2021-06-20 17:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0025_alter_subscriptionplan_spacial_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subscriptionplan',
            name='spacial_id',
            field=models.CharField(default='ab1e45d8', max_length=8),
        ),
    ]
