# Generated by Django 3.2.3 on 2021-06-30 14:20

import accounts.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0026_alter_subscriptionplan_spacial_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subscriptionplan',
            name='spacial_id',
            field=models.CharField(default=accounts.models.generate_random_uuid, max_length=8),
        ),
    ]
