# Generated by Django 3.2.3 on 2021-07-13 15:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0027_alter_subscriptionplan_spacial_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='is_censor_on',
            field=models.BooleanField(default=True),
        ),
    ]
