# Generated by Django 3.2.3 on 2021-08-12 17:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0028_userprofile_is_censor_on'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='subscription',
            options={'verbose_name': 'مدیریت اشتراک کاربران', 'verbose_name_plural': 'مدیریت اشتراک کاربران'},
        ),
        migrations.AlterModelOptions(
            name='subscriptionplan',
            options={'verbose_name': 'مدیریت نوع اشتراک', 'verbose_name_plural': 'مدیریت نوع اشتراک'},
        ),
        migrations.AlterModelOptions(
            name='userprofile',
            options={'verbose_name': 'حساب کاربری', 'verbose_name_plural': 'حساب کاربری'},
        ),
    ]
