# Generated by Django 3.2.3 on 2021-09-30 00:08

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Imdb',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('link', models.CharField(max_length=500, verbose_name='لینک')),
                ('celery_id', models.CharField(blank=True, max_length=500, null=True, verbose_name='شناسه')),
                ('status', models.CharField(blank=True, max_length=50, null=True, verbose_name='وضعیت')),
                ('is_done', models.BooleanField(default=False)),
            ],
        ),
    ]
