# Generated by Django 3.2.3 on 2021-10-05 08:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('imdb_scraper', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ImdbScraperTest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('test_url', models.CharField(blank=True, max_length=255, null=True)),
                ('TitleText', models.CharField(blank=True, max_length=255, null=True)),
                ('TitleMetaDataContainer', models.CharField(blank=True, max_length=255, null=True)),
                ('content_type_role', models.CharField(blank=True, max_length=255, null=True)),
                ('ActorName', models.CharField(blank=True, max_length=255, null=True)),
                ('rating', models.CharField(blank=True, max_length=255, null=True)),
                ('TextContainerBreakpointXL', models.CharField(blank=True, max_length=255, null=True)),
                ('director_a', models.CharField(blank=True, max_length=255, null=True)),
                ('GenreChip', models.CharField(blank=True, max_length=255, null=True)),
                ('hero_media_a', models.CharField(blank=True, max_length=255, null=True)),
                ('TotalRatingAmount', models.CharField(blank=True, max_length=255, null=True)),
                ('country_a', models.CharField(blank=True, max_length=255, null=True)),
            ],
        ),
    ]
