# Generated by Django 3.2.3 on 2021-10-08 09:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('imdb_scraper', '0002_imdbscrapertest'),
    ]

    operations = [
        migrations.AddField(
            model_name='imdb',
            name='log',
            field=models.TextField(blank=True, max_length=10000, null=True),
        ),
    ]
