# Generated by Django 3.2.3 on 2021-06-19 17:00

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Robots',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('select_type', models.CharField(choices=[('a', 'مجاز'), ('d', 'غیر مجاز')], default='a', max_length=1, verbose_name='وع')),
                ('value', models.CharField(default='/', max_length=255, verbose_name='مقدار')),
            ],
        ),
    ]
