# Generated by Django 3.2.3 on 2021-06-19 17:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('robots_txt', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='robots',
            options={'verbose_name': 'آدرس', 'verbose_name_plural': 'روبات'},
        ),
        migrations.AlterField(
            model_name='robots',
            name='select_type',
            field=models.CharField(choices=[('Allow', 'مجاز'), ('Disallow', 'غیر مجاز')], default='Allow', max_length=8, verbose_name='وع'),
        ),
    ]
