# Generated by Django 3.2.3 on 2021-06-19 17:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('robots_txt', '0002_auto_20210619_2139'),
    ]

    operations = [
        migrations.AlterField(
            model_name='robots',
            name='value',
            field=models.CharField(default='', max_length=255, verbose_name='مقدار'),
        ),
    ]
