# Generated by Django 3.2.3 on 2021-06-19 17:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('robots_txt', '0003_alter_robots_value'),
    ]

    operations = [
        migrations.AlterField(
            model_name='robots',
            name='select_type',
            field=models.CharField(choices=[('Allow', 'مجاز'), ('Disallow', 'غیر مجاز')], default='Allow', max_length=8, verbose_name='نوع'),
        ),
    ]
