# Generated by Django 3.2.3 on 2021-06-19 18:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('robots_txt', '0004_alter_robots_select_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='robots',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
