# Generated by Django 3.2.3 on 2021-07-12 20:04

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='invitor_code',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=11)),
                ('invitations', models.IntegerField()),
                ('invited_users', models.ManyToManyField(related_name='invited_users', to=settings.AUTH_USER_MODEL)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='myuser', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'کد معرف',
                'verbose_name_plural': 'کدهای معرف',
            },
        ),
        migrations.CreateModel(
            name='generated_invitor_code',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=11)),
                ('invitations', models.IntegerField()),
                ('invited_users', models.ManyToManyField(related_name='invited_users_g', to=settings.AUTH_USER_MODEL)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_g', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'کد معرف دستی',
                'verbose_name_plural': 'کدهای معرف دستی',
            },
        ),
    ]
