# Generated by Django 3.2.3 on 2021-07-24 10:49

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('invitor', '0002_auto_20210713_2027'),
    ]

    operations = [
        migrations.AlterField(
            model_name='generated_invitor_code',
            name='invitations',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='generated_invitor_code',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='user_g', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='invitor_code',
            name='invitations',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
