# Generated by Django 3.2.3 on 2021-06-20 15:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('giftcard', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='giftcard_related_to_user',
            name='gift_code',
        ),
        migrations.RemoveField(
            model_name='giftcard_related_to_user',
            name='user',
        ),
        migrations.DeleteModel(
            name='GiftCard',
        ),
        migrations.DeleteModel(
            name='GiftCard_Related_to_User',
        ),
    ]
