# Generated by Django 3.2.3 on 2021-06-20 15:41

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('movies', '0001_initial'),
        ('giftcard', '0002_auto_20210620_2006'),
    ]

    operations = [
        migrations.CreateModel(
            name='GiftCard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='', max_length=200, verbose_name='عنوان')),
                ('code', models.CharField(default='9354ee91', max_length=8, verbose_name='کد کارت هدیه')),
                ('valid_from', models.DateTimeField(help_text=('در این فیلد تعیین کنید از چه زمانی کارت هدیه فعال باشد',), verbose_name='فعال از')),
                ('valid_to', models.DateTimeField(help_text=('در  این فیلد تعریف کنید کارت هدیه تا چه زمانی فعال باشد',), verbose_name='زمان پایان')),
                ('valid_day', models.IntegerField(help_text=('در  این فیلد تعریف کنید کارت هدیه تا چند روز اعتبار دارد',), verbose_name='مدت اعتبار')),
                ('active', models.BooleanField(default=False, verbose_name='وضعیت')),
                ('category', models.ManyToManyField(related_name='category', to='movies.Category', verbose_name='دسته ها')),
            ],
            options={
                'verbose_name': 'کارت هدیه',
                'verbose_name_plural': 'کارت های هدیه',
            },
        ),
        migrations.CreateModel(
            name='GiftCard_Related_to_User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_enabeld', models.DateTimeField(default=django.utils.timezone.now)),
                ('status', models.BooleanField(default=True, verbose_name='وضعیت استفاده')),
                ('gift_code', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='giftcard', to='giftcard.giftcard')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='user', to=settings.AUTH_USER_MODEL, verbose_name='کاربر')),
            ],
            options={
                'verbose_name': 'وضعیت کارت هدیه',
                'verbose_name_plural': 'وضعیت کارت های هدیه',
            },
        ),
    ]
