# Generated by Django 3.2.3 on 2021-06-20 15:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('giftcard', '0003_giftcard_giftcard_related_to_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='giftcard',
            name='code',
            field=models.CharField(default='94a41375', max_length=8, verbose_name='کد کارت هدیه'),
        ),
    ]
