# Generated by Django 3.2.3 on 2021-06-20 16:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('giftcard', '0007_alter_giftcard_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='giftcard',
            name='code',
            field=models.CharField(default='b31617c0', max_length=8, verbose_name='کد کارت هدیه'),
        ),
    ]
