# Generated by Django 3.2.3 on 2021-06-30 16:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('giftcard', '0011_alter_giftcard_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='giftcard',
            name='code',
            field=models.CharField(default='0a21ce04', max_length=255, unique=True, verbose_name='کد کارت هدیه'),
        ),
    ]
