# Generated by Django 3.2.3 on 2021-07-24 10:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('giftcard', '0017_alter_giftcard_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='giftcard',
            name='code',
            field=models.CharField(default='3e730d09', max_length=255, unique=True, verbose_name='کد کارت هدیه'),
        ),
    ]
