# Generated by Django 3.2.3 on 2021-08-03 08:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('giftcard', '0018_alter_giftcard_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='giftcard',
            name='code',
            field=models.CharField(default='ea9e13c8', max_length=255, unique=True, verbose_name='کد کارت هدیه'),
        ),
    ]
