# Generated by Django 3.2.3 on 2021-08-03 17:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('giftcard', '0019_alter_giftcard_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='giftcard',
            name='code',
            field=models.CharField(default='61e26832', max_length=255, unique=True, verbose_name='کد کارت هدیه'),
        ),
    ]
