# Generated by Django 3.2.3 on 2021-06-21 15:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='actor',
            name='name',
            field=models.CharField(max_length=35, unique=True, verbose_name='نام بازیگر'),
        ),
        migrations.AlterField(
            model_name='director',
            name='name',
            field=models.CharField(max_length=35, unique=True, verbose_name='نام کارگردان'),
        ),
        migrations.AlterField(
            model_name='playlist',
            name='name_en',
            field=models.CharField(max_length=55, unique=True, verbose_name='نام انگلیسی'),
        ),
        migrations.AlterField(
            model_name='playlist',
            name='name_fa',
            field=models.CharField(max_length=55, unique=True, verbose_name='نام فارسی'),
        ),
    ]
