# Generated by Django 3.2.3 on 2021-08-03 08:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0002_auto_20210621_2000'),
    ]

    operations = [
        migrations.AddField(
            model_name='playlist',
            name='img1536x778',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
