# Generated by Django 3.2.3 on 2021-08-03 17:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0003_playlist_img1536x778'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='', verbose_name='تصویر دسته بندی'),
        ),
    ]
