# Generated by Django 3.2.3 on 2021-08-08 04:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0004_category_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='playlist',
            name='img300x300',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
