# Generated by Django 3.2.3 on 2021-08-12 17:47

from django.db import migrations, models
import movies.models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0005_playlist_img300x300'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='episode',
            name='is_available_in_1080p',
        ),
        migrations.RemoveField(
            model_name='episode',
            name='is_available_in_720p',
        ),
        migrations.RemoveField(
            model_name='playlist',
            name='img1536x778',
        ),
        migrations.RemoveField(
            model_name='playlist',
            name='img300x300',
        ),
        migrations.AddField(
            model_name='playlist',
            name='image_1920x1080',
            field=models.ImageField(blank=True, null=True, upload_to=movies.models.image_path, verbose_name='تصویر بنر دسکتاپ فیلم'),
        ),
        migrations.AddField(
            model_name='playlist',
            name='image_600x810',
            field=models.ImageField(blank=True, null=True, upload_to=movies.models.image_path, verbose_name='تصویر بنر موبایل فیلم'),
        ),
        migrations.AlterField(
            model_name='playlist',
            name='thumb_image',
            field=models.ImageField(blank=True, null=True, upload_to=movies.models.image_path, verbose_name='تصویر انگشتی فیلم'),
        ),
    ]
