# Generated by Django 3.2.3 on 2021-09-28 15:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0006_auto_20210812_2217'),
    ]

    operations = [
        migrations.AlterField(
            model_name='playlist',
            name='year',
            field=models.CharField(max_length=10, verbose_name='سال'),
        ),
    ]
